{
  "uid": "d4206c4c4fee14ab",
  "name": "test_sub_unusual[sub_unusual_data2]",
  "fullName": "test_calc.TestSub#test_sub_unusual",
  "historyId": "ca523e135bb68b8f88df35d1d4ed0801",
  "time": {
    "start": 1597675959399,
    "stop": 1597675959399,
    "duration": 0
  },
  "status": "skipped",
  "statusMessage": "TypeError: unsupported operand type(s) for -: 'str' and 'str'",
  "statusTrace": "self = <Hogwarts_pytest_zuoye.testcode.test_calc.TestSub object at 0x000001FEF97186D8>, calc_init = <sourcecode.calc_code.Calculator object at 0x000001FEF96C42B0>, sub_unusual_data = ['rt', 't', 'r']\n\n    @pytest.mark.xfail(raises=TypeError)  # 预估返回类型错误\n    def test_sub_unusual(self, calc_init, sub_unusual_data):\n>       result = calc_init.sub(sub_unusual_data[0], sub_unusual_data[1])\n\ntest_calc.py:72: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <sourcecode.calc_code.Calculator object at 0x000001FEF96C42B0>, a = 'rt', b = 't'\n\n    def sub(self, a, b):\n>       return a - b\nE       TypeError: unsupported operand type(s) for -: 'str' and 'str'\n\n..\\sourcecode\\calc_code.py:8: TypeError",
  "flaky": false,
  "newFailed": false,
  "beforeStages": [
    {
      "name": "sub_unusual_data",
      "time": {
        "start": 1597675959399,
        "stop": 1597675959399,
        "duration": 0
      },
      "status": "passed",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "shouldDisplayMessage": false,
      "attachmentsCount": 0,
      "hasContent": false,
      "stepsCount": 0
    },
    {
      "name": "calc_init",
      "time": {
        "start": 1597675959371,
        "stop": 1597675959371,
        "duration": 0
      },
      "status": "passed",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "shouldDisplayMessage": false,
      "attachmentsCount": 0,
      "hasContent": false,
      "stepsCount": 0
    }
  ],
  "testStage": {
    "status": "skipped",
    "statusMessage": "TypeError: unsupported operand type(s) for -: 'str' and 'str'",
    "statusTrace": "self = <Hogwarts_pytest_zuoye.testcode.test_calc.TestSub object at 0x000001FEF97186D8>, calc_init = <sourcecode.calc_code.Calculator object at 0x000001FEF96C42B0>, sub_unusual_data = ['rt', 't', 'r']\n\n    @pytest.mark.xfail(raises=TypeError)  # 预估返回类型错误\n    def test_sub_unusual(self, calc_init, sub_unusual_data):\n>       result = calc_init.sub(sub_unusual_data[0], sub_unusual_data[1])\n\ntest_calc.py:72: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <sourcecode.calc_code.Calculator object at 0x000001FEF96C42B0>, a = 'rt', b = 't'\n\n    def sub(self, a, b):\n>       return a - b\nE       TypeError: unsupported operand type(s) for -: 'str' and 'str'\n\n..\\sourcecode\\calc_code.py:8: TypeError",
    "steps": [],
    "attachments": [
      {
        "uid": "228f9100d2fc87e3",
        "name": "stdout",
        "source": "228f9100d2fc87e3.txt",
        "type": "text/plain",
        "size": 19
      }
    ],
    "parameters": [],
    "shouldDisplayMessage": true,
    "attachmentsCount": 1,
    "hasContent": true,
    "stepsCount": 0
  },
  "afterStages": [
    {
      "name": "calc_init::0",
      "time": {
        "start": 1597675959405,
        "stop": 1597675959405,
        "duration": 0
      },
      "status": "passed",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "shouldDisplayMessage": false,
      "attachmentsCount": 0,
      "hasContent": false,
      "stepsCount": 0
    }
  ],
  "labels": [
    {
      "name": "tag",
      "value": "run(order=2)"
    },
    {
      "name": "tag",
      "value": "@pytest.mark.xfail(raises=<class 'TypeError'>)"
    },
    {
      "name": "tag",
      "value": "sub"
    },
    {
      "name": "suite",
      "value": "test_calc"
    },
    {
      "name": "subSuite",
      "value": "TestSub"
    },
    {
      "name": "host",
      "value": "TJ-YF-262JLJ"
    },
    {
      "name": "thread",
      "value": "4968-MainThread"
    },
    {
      "name": "framework",
      "value": "pytest"
    },
    {
      "name": "language",
      "value": "cpython3"
    },
    {
      "name": "package",
      "value": "test_calc"
    },
    {
      "name": "resultFormat",
      "value": "allure2"
    }
  ],
  "parameters": [
    {
      "name": "sub_unusual_data",
      "value": "['rt', 't', 'r']"
    }
  ],
  "links": [],
  "hidden": false,
  "retry": false,
  "extra": {
    "severity": "normal",
    "retries": [],
    "categories": [],
    "tags": [
      "run(order=2)",
      "sub",
      "@pytest.mark.xfail(raises=<class 'TypeError'>)"
    ]
  },
  "source": "d4206c4c4fee14ab.json",
  "parameterValues": [
    "['rt', 't', 'r']"
  ]
}